### global variables
@baseUrl = http://localhost:8000
@contentType = application/json

@loginPath = /api/login

### user login 
POST {{baseUrl}}{{loginPath}}
Content-Type: {{contentType}}

{
    "seatNo": "5692",
    "ssn": "30009220300112"
}

