### global variables
@baseUrl = http://localhost:8000
@contentType = application/json

@studentPath = /api/students

### get all
GET {{baseUrl}}{{studentPath}}

### get by id
GET {{baseUrl}}{{studentPath}}/5ef6eeeb1c87aa15942f1c8d

### add new student
POST  {{baseUrl}}{{studentPath}}
Content-Type: {{contentType}}

{
    "seatNo": "0000",
    "ssn": "00000000000000",
    "fullName": "test student"
}

### delete 
DELETE  {{baseUrl}}{{studentPath}}/5ef5e2381769a72218fe477c

### update
PUT   {{baseUrl}}{{studentPath}}/5ef6eeeb1c87aa15942f1c8d
Content-Type: {{contentType}}

{
    "seatNo": "0000",
    "ssn": "01230000000000",
    "fullName": "test student updated"
}